version: 3

tasks:
  generate:
    aliases:
      - gen
    desc: "generate code from proto files for Golang"
    cmds:
      - protoc -I proto proto/cm/cm.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative